[functions]

  [functions."*"]
  included_files = [
    ".netlify/**/*",
    ".env",
    ".env.production",
    ".env.local",
    ".env.production.local"
  ]

[build]
command = "npm run build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[headers]]
for = "/_next/static/*"

  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/_next/image"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200

  [redirects.query]
  url = ":url"
  w = ":width"
  q = ":quality"

[[redirects]]
from = "/_ipx/*"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200

  [redirects.query]
  url = ":url"
  w = ":width"
  q = ":quality"

[context]

  [context.dev]

    [context.dev.functions]

      [context.dev.functions."*"]
      included_files = [
        ".netlify/**/*",
        ".env",
        ".env.production",
        ".env.local",
        ".env.production.local"
      ]

    [[context.dev.headers]]
    for = "/_next/static/*"

      [context.dev.headers.values]
      Cache-Control = "public, max-age=31536000, immutable"

  [context.main]

    [context.main.functions]

      [context.main.functions."*"]
      included_files = [
        ".netlify/**/*",
        ".env",
        ".env.production",
        ".env.local",
        ".env.production.local"
      ]

    [[context.main.headers]]
    for = "/_next/static/*"

      [context.main.headers.values]
      Cache-Control = "public, max-age=31536000, immutable"